import type { AppState } from "./types";

export const initialState: AppState = {
  role: "fan",
  venueId: "metlife",
  matchMinute: 0,
  matchState: "T-75 pre-match",
  matchPhase: "pre-match",
  selectedView: "dashboard",
  sectors: [
    { id: "north", name: "North Concourse", density: 3.2, trend: 0.3 },
    { id: "east", name: "East Plaza", density: 4.8, trend: 0.7 },
    { id: "south", name: "South Stands", density: 5.7, trend: 0.4 },
    { id: "west", name: "West Gate Hall", density: 2.6, trend: -0.1 },
    { id: "field", name: "Lower Bowl", density: 3.9, trend: 0.2 },
  ],
  gates: [
    { id: "A", name: "Gate A", waitMinutes: 16, throughputPerMin: 74, targetThroughputPerMin: 110 },
    { id: "B", name: "Gate B", waitMinutes: 7, throughputPerMin: 118, targetThroughputPerMin: 115 },
    { id: "C", name: "Gate C", waitMinutes: 11, throughputPerMin: 91, targetThroughputPerMin: 110 },
    { id: "D", name: "Gate D", waitMinutes: 4, throughputPerMin: 120, targetThroughputPerMin: 105 },
  ],
  queues: [
    { id: "q1", name: "Restroom 112", type: "Restroom", waitMinutes: 9, arrivalRate: 18, serviceRate: 15, trend: 1 },
    { id: "q2", name: "Restroom 219", type: "Restroom", waitMinutes: 4, arrivalRate: 12, serviceRate: 15, trend: 0 },
    { id: "q3", name: "Tacos Stand 105", type: "Food", waitMinutes: 13, arrivalRate: 21, serviceRate: 16, trend: 1 },
    { id: "q4", name: "Water Refill East", type: "Water", waitMinutes: 3, arrivalRate: 20, serviceRate: 28, trend: -1 },
    { id: "q5", name: "Merch 240", type: "Retail", waitMinutes: 8, arrivalRate: 10, serviceRate: 8, trend: 0 },
  ],
  incidents: [
    {
      id: "INC-1001",
      type: "Medical",
      location: "South Stands",
      crowdDensity: 5.7,
      minutesToKickoff: 35,
      status: "open",
      createdAt: Date.now() - 240000,
    },
    {
      id: "INC-1002",
      type: "Spill",
      location: "Gate B ramp",
      crowdDensity: 3.4,
      minutesToKickoff: 35,
      status: "open",
      createdAt: Date.now() - 420000,
    },
    {
      id: "INC-1003",
      type: "Security",
      location: "East Plaza",
      crowdDensity: 4.8,
      minutesToKickoff: 35,
      status: "open",
      createdAt: Date.now() - 120000,
    },
  ],
  transit: [
    {
      id: "rail",
      mode: "Rail",
      name: "Meadowlands event rail",
      eta: 12,
      load: "Amber",
      note: "Next three trains routed through Secaucus.",
    },
    {
      id: "shuttle",
      mode: "Shuttle",
      name: "Accessible shuttle loop",
      eta: 6,
      load: "Green",
      note: "Two low-floor shuttles staged at Lot E.",
    },
    {
      id: "rideshare",
      mode: "Ride-share",
      name: "Remote pickup zone",
      eta: 18,
      load: "Amber",
      note: "Post-match walk time currently 14 min.",
    },
  ],
  sustainability: {
    fans: 67100,
    transportKgCO2e: 128600,
    renewableEnergyPct: 64,
    gridLoadPct: 71,
    waterSavedLiters: 182000,
    wasteDiversionPct: 68,
  },
  decisions: [
    {
      id: "d1",
      title: "Meter Gate A inflow",
      body: "Wait is 16 min. Divert 25% of arrivals to Gate D.",
      severity: "Amber",
      confidence: 0.88,
      createdAt: Date.now() - 60000,
    },
    {
      id: "d2",
      title: "Watch South Stands",
      body: "Density at 5.7 persons/m² with upward trend. Pre-stage stewards.",
      severity: "Amber",
      confidence: 0.84,
      createdAt: Date.now() - 180000,
    },
  ],
  blockedExits: ["south"],
  myTicket: {
    section: "104",
    assignedGate: "A",
    ticketNo: "T-10488",
    batch: 3,
  },
  liveMatches: {
    metlife: { teams: "USA vs. Germany", score: "2-1", time: "18:30 kickoff" },
    sofi: { teams: "Mexico vs. Brazil", score: "0-0", time: "20:00 kickoff" },
    sofistadium: { teams: "Mexico vs. Brazil", score: "0-0", time: "20:00 kickoff" },
    azteca: { teams: "Canada vs. Argentina", score: "1-3", time: "Final" },
    att: { teams: "England vs. France", score: "1-1", time: "75'" },
    bmo: { teams: "Japan vs. Spain", score: "0-2", time: "Halftime" },
  },
  highContrast: false,
  largeText: false,
  weather: {
    temperature: 22,
    humidity: 65,
    windSpeed: 8,
    condition: "sunny",
  },
  sectorMap: {},
};
